import { convert as htmlToPlainText } from "html-to-text";
import { TOKEN_LIMITS } from "../core/config.js";
import {
  resolveChapterNumberForChapter,
  resolveChapterOutlineForChapter,
} from "../services/projects/chapterOutline.js";

interface PromptProject {
  id: string;
  title: string;
  description: string;
  genre: string;
  content: string;
  wordCount: number;
  chapters: PromptChapter[];
  storyBible: PromptStoryBible | null;
  createdAt: string;
  updatedAt: string;
}

interface PromptChapter {
  id: string;
  title: string;
  content: string;
  wordCount: number;
  order: number;
}

interface PromptChapterOutline {
  chapterNumber: number;
  title: string;
  summary: string;
  beats: string[];
  characters: string[];
  location: string;
  timeframe: string;
}

interface PromptStoryBible {
  premise: {
    logline: string;
    synopsis: string;
    themes: string[];
    tone: string;
    genre: string;
  };
  characters: PromptCharacter[];
  world: {
    setting: string;
    timePeriod: string;
    locations: PromptLocation[];
    rules: string[];
  };
  plotStructure: {
    acts: Array<{
      number: number;
      name: string;
      description: string;
      keyEvents: string[];
      chapterRange?: { start: number; end: number };
    }>;
    plotThreads: PromptPlotThread[];
  };
  chapterOutlines: PromptChapterOutline[];
  styleDirectives: {
    pov: string;
    tense: string;
    proseStyle: string;
    dialogueStyle: string;
  };
}

interface PromptCharacter {
  id: string;
  name: string;
  nicknames?: string[];
  role: string;
  description: string;
  backstory: string;
  motivation: string;
  fears: string[];
  flaw: string;
  arc: string;
  unrevealed?: boolean;
  spoilers?: string[];
  voice: {
    vocabulary: string;
    speechPatterns: string[];
    catchphrases: string[];
  };
  relationships: PromptRelationship[];
  autoGenerated?: boolean;
  cognitiveFilter?: {
    primaryMode:
      | "analytical"
      | "emotional"
      | "instinctive"
      | "ritualistic"
      | "detached"
      | "sensory";
    internalLanguage: string;
    blindSpot: string;
    repeatingThoughtLoop: string;
    forbiddenWords?: string[];
    signatureThoughts?: string[];
  };
}

interface PromptRelationship {
  characterId: string;
  type: string;
  description: string;
}

interface PromptLocation {
  name: string;
  description: string;
  significance: string;
  autoGenerated?: boolean;
}

interface PromptPlotThread {
  id: string;
  name: string;
  type: string;
  description: string;
  status: string;
  introducedIn?: number | null;
  resolvedIn?: number | null;
  currentState?: string;
  nextMilestone?: string;
}

interface PromptStyleFingerprint {
  vocabularyComplexity: number;
  avgSentenceLength: number;
  dialogueRatio: number;
  showVsTellRatio: number;
  passiveVoiceRatio: number;
  adverbDensity: number;
  metaphorFrequency: number;
  pacingScore: number;
  toneDescriptor: string;
  strengthAreas: string[];
  improvementAreas: string[];
  sampleCount: number;
  rawSamples: string[];
  signaturePhrases: string[];
  dialogueTags: { preferred: string[]; avoided: string[] };
  verbChoices: { movement: string[]; speech: string[]; emotion: string[] };
  sentencePatterns: string[];
  paragraphOpeners: string[];
  sceneOpenings: string[];
  tensionTechniques: string[];
  exemplars: string[];
  humorStyle: string;
  emotionalPalette: string[];
  avoidances: string[];
  proseTechniques: string[];
  pacing: string;
}

interface PromptCraftPattern {
  id: string;
  category: string;
  pattern: string;
  example: string;
  effectiveness: number;
}

interface PromptLifetimeInsight {
  id: string;
  type: string;
  content: string;
  strength: number;
  createdAt: string;
}

interface PromptPreferenceMemory {
  preferredPov: string;
  preferredTense: string;
  contextWindowSize: number;
  enableContinuityChecks: boolean;
  persistentDirections?: string;
}

interface PromptProjectMemory {
  authorDirections: string[];
  projectPreferences: string[];
  projectEvents: string[];
}

interface PromptNarrativeState {
  time: string;
  location: string;
  povCharacter: string;
  mood: string;
}

interface PromptContextWindow {
  before: string;
  after: string;
  cursorPosition: number;
}

interface PromptContinuityIndex {
  characters: Map<
    string,
    {
      lastLocation: string;
      lastEmotion: string;
      lastAction: string;
      relationships: Record<string, string>;
      updatedAt: number;
    }
  >;
  plotThreads: Map<
    string,
    {
      status: "active" | "resolved" | "paused";
      lastMention: string;
      triggers: string[];
    }
  >;
  worldState: {
    currentTime: string;
    currentLocation: string;
    recentEvents: string[];
  };
  projectHash: string;
}

interface AutonomousPromptState {
  mandatoryBeat?: string;
  completedBeats?: string[];
  remainingPlotPoints?: string[];
  selectedThreadIds?: string[];
  mode?: "chapter" | "book";
}

interface RelevantBeatSelection {
  beats: string[];
  indexes: number[];
  bridgeToAfterText: boolean;
}

export interface CuratedPromptBuildOptions {
  project: PromptProject;
  contextWindow: PromptContextWindow;
  userPrompt: string;
  chapterId?: string;
  sceneDirective?: string;
  styleFingerprint?: PromptStyleFingerprint | null;
  craftPatterns?: PromptCraftPattern[];
  lifetimeInsights?: PromptLifetimeInsight[];
  preferenceMemory?: PromptPreferenceMemory;
  projectMemory?: PromptProjectMemory;
  narrativeState?: PromptNarrativeState;
  continuityIndex?: PromptContinuityIndex;
  generationMode?: "interactive" | "autonomous";
  autonomousState?: AutonomousPromptState;
}

export interface CuratedPromptBuildResult {
  systemPrompt: string;
  userMessage: string;
  selectionSummary: {
    mode: "interactive" | "autonomous";
    chapterTitle: string | null;
    characterNames: string[];
    locationNames: string[];
    plotThreads: string[];
    worldRules: number;
    craftPatterns: number;
    lifetimeInsights: number;
    projectMemoryEntries: number;
    usedStoryBible: boolean;
    usedStyleFingerprint: boolean;
    usedPreferenceMemory: boolean;
    usedPlannerBrief: boolean;
  };
}

interface LegacyScenePlan {
  directive: string;
  selectedEvidence?: Array<{
    id?: string;
    source: string;
    text: string;
    score?: number;
  }>;
}

interface BuildCuratedPromptOptions {
  project: PromptProject;
  contextWindow: PromptContextWindow;
  userPrompt: string;
  chapterId?: string;
  scenePlan?: LegacyScenePlan | null;
  styleFingerprint?: PromptStyleFingerprint | null;
  craftPatterns?: PromptCraftPattern[];
  lifetimeInsights?: PromptLifetimeInsight[];
  preferenceMemory?: PromptPreferenceMemory;
  projectMemory?: PromptProjectMemory;
  narrativeState?: PromptNarrativeState;
  continuityIndex?: PromptContinuityIndex;
  selectedThreadIds?: string[];
  mandatoryBeat?: string;
  completedBeats?: string[];
  remainingPlotPoints?: string[];
  mode?: "manual" | "autonomous";
}

const PROMPT_CONTEXT_LIMITS = {
  interactiveBefore: 100000,
  interactiveAfter: 40000,
  autonomousBefore: 75000,
  synopsis: 4000,
  description: 1200,
  motivation: 800,
  relationship: 600,
  plotThread: 1200,
  rule: 800,
} as const;

function clip(text: string, maxChars: number): string {
  if (maxChars <= 0) return "";
  if (text.length <= maxChars) return text;
  return `${text.slice(0, maxChars - 1).trim()}...`;
}

function clipTail(text: string, maxChars: number): string {
  if (maxChars <= 0) return "";
  if (text.length <= maxChars) return text;
  return `...${text.slice(text.length - maxChars + 3).trim()}`;
}

function cleanLineBreaks(text: string): string {
  return text
    .replace(/\r/g, "")
    .replace(/[ \t]+\n/g, "\n")
    .replace(/\n{3,}/g, "\n\n")
    .trim();
}

function normalizeNarrativeText(text: string): string {
  if (!text) return "";
  try {
    if (/[<>]/.test(text)) {
      return cleanLineBreaks(htmlToPlainText(text, { wordwrap: false }));
    }
  } catch {
    return cleanLineBreaks(text.replace(/<[^>]+>/g, " "));
  }
  return cleanLineBreaks(text);
}

function tokenize(text: string): Set<string> {
  return new Set(
    text
      .toLowerCase()
      .replace(/[^a-z0-9\s]/g, " ")
      .split(/\s+/)
      .filter((token) => token.length > 2),
  );
}

function lexicalOverlap(a: string, b: string): number {
  const left = tokenize(a);
  const right = tokenize(b);
  if (left.size === 0 || right.size === 0) return 0;

  let overlap = 0;
  for (const token of left) {
    if (right.has(token)) overlap++;
  }

  return overlap / Math.max(left.size, right.size);
}

function escapeRegExp(value: string): string {
  return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

function isNumericCodename(value: string): boolean {
  return /^(zero|one|two|three|four|five|six|seven|eight|nine|ten|eleven|twelve|thirteen|fourteen|fifteen|\d+)$/i.test(
    value.trim(),
  );
}

function buildAliasPattern(alias: string): RegExp | null {
  const normalized = alias.trim();
  if (!normalized) return null;

  const escaped = escapeRegExp(normalized).replace(/\s+/g, "\\s+");
  if (isNumericCodename(normalized)) {
    return new RegExp(`(?<!asset\\s)(?<!agent\\s)\\b${escaped}\\b`, "i");
  }

  return new RegExp(`\\b${escaped}\\b`, "i");
}

function aliasMentions(text: string, aliases: string[]): number {
  const haystack = text.toLowerCase();
  let hits = 0;

  for (const alias of aliases) {
    const normalized = alias.trim().toLowerCase();
    if (!normalized) continue;
    if (normalized.length < 3 && !isNumericCodename(normalized)) continue;
    const pattern = buildAliasPattern(normalized);
    if (pattern?.test(haystack)) hits++;
  }

  return hits;
}

function findCurrentChapter(
  project: PromptProject,
  chapterId?: string,
): PromptChapter | undefined {
  if (!chapterId) return undefined;
  return project.chapters.find((chapter) => chapter.id === chapterId);
}

function findCurrentOutline(
  project: PromptProject,
  chapterId?: string,
): PromptChapterOutline | undefined {
  const chapter = findCurrentChapter(project, chapterId);
  return resolveChapterOutlineForChapter(
    chapter,
    project.storyBible?.chapterOutlines,
  );
}

function findCurrentChapterNumber(
  project: PromptProject,
  chapterId?: string,
): number | undefined {
  const chapter = findCurrentChapter(project, chapterId);
  return resolveChapterNumberForChapter(
    chapter,
    project.storyBible?.chapterOutlines,
  );
}

function isValueVisibleInLocalScene(text: string, value: string): boolean {
  return aliasMentions(text, [value]) > 0;
}

function buildCharacterAliases(
  character: PromptCharacter,
  _localSceneText: string,
  _generationMode: "interactive" | "autonomous",
): string[] {
  const aliases = [character.name, ...(character.nicknames || [])];
  return [...new Set(aliases.filter(Boolean))];
}

function isCharacterSafeForLocalPrompt(
  _character: PromptCharacter,
  _localSceneText: string,
  _generationMode: "interactive" | "autonomous",
): boolean {
  return true;
}

function summarizeCharacter(
  character: PromptCharacter,
  allCharacters: PromptCharacter[],
  narrativeState?: PromptNarrativeState,
  generationMode: "interactive" | "autonomous" = "interactive",
  localSceneText = "",
): string[] {
  const lines: string[] = [];
  lines.push(
    `- ${character.name} (${character.role}): ${clip(character.description || "No description recorded.", PROMPT_CONTEXT_LIMITS.description)}`,
  );

  if (generationMode === "interactive") {
    if (
      character.voice?.speechPatterns?.length &&
      isValueVisibleInLocalScene(localSceneText, character.name)
    ) {
      lines.push(
        `  Voice cues: ${character.voice.speechPatterns.slice(0, 2).join(", ")}`,
      );
    }
    return lines;
  }

  if (character.motivation) {
    lines.push(
      `  Wants: ${clip(character.motivation, PROMPT_CONTEXT_LIMITS.motivation)}`,
    );
  }

  if (character.arc) {
    lines.push(
      `  Arc pressure: ${clip(character.arc, PROMPT_CONTEXT_LIMITS.motivation)}`,
    );
  }

  if (character.voice?.speechPatterns?.length) {
    lines.push(
      `  Voice cues: ${character.voice.speechPatterns.slice(0, 3).join(", ")}`,
    );
  }

  const povMatch = narrativeState?.povCharacter
    ? aliasMentions(narrativeState.povCharacter, [
        character.name,
        ...(character.nicknames || []),
      ]) > 0
    : false;

  if (povMatch && character.cognitiveFilter) {
    const filter = character.cognitiveFilter;
    lines.push(
      `  POV filter: ${filter.primaryMode}; ${clip(filter.internalLanguage, 120)}`,
    );
    if (filter.forbiddenWords?.length) {
      lines.push(
        `  Avoid internal wording: ${filter.forbiddenWords.slice(0, 4).join(", ")}`,
      );
    }
  }

  const relationshipSummaries = (character.relationships || [])
    .map((relationship) => {
      const target = allCharacters.find(
        (candidate) => candidate.id === relationship.characterId,
      );
      if (!target) return null;
      return `${target.name}=${clip(relationship.type || relationship.description || "linked", PROMPT_CONTEXT_LIMITS.relationship)}`;
    })
    .filter((entry): entry is string => Boolean(entry));

  if (relationshipSummaries.length > 0) {
    lines.push(
      `  Relationship pressure: ${relationshipSummaries.slice(0, 3).join("; ")}`,
    );
  }

  return lines;
}

function _scoreCharacter(
  character: PromptCharacter,
  focusText: string,
  recentText: string,
  outline?: PromptChapterOutline,
  narrativeState?: PromptNarrativeState,
  generationMode: "interactive" | "autonomous" = "interactive",
  localSceneText = "",
): number {
  const aliases = buildCharacterAliases(
    character,
    localSceneText,
    generationMode,
  );
  const localSceneLocked =
    generationMode === "interactive" && localSceneText.trim().length > 300;
  let score = 0;

  if (
    !isCharacterSafeForLocalPrompt(character, localSceneText, generationMode)
  ) {
    return 0;
  }

  const localHits = aliasMentions(localSceneText, aliases);
  const povMatch = narrativeState?.povCharacter
    ? aliasMentions(narrativeState.povCharacter, aliases) > 0
    : false;

  if (localSceneLocked && localHits === 0 && !povMatch) {
    return 0;
  }

  if (outline?.characters?.some((name) => aliasMentions(name, aliases) > 0))
    score += 12;
  if (povMatch) score += 14;
  score += localHits * 7;
  score += aliasMentions(focusText, aliases) * 5;
  score += aliasMentions(recentText, aliases) * 3;
  score +=
    lexicalOverlap(
      focusText,
      `${character.description} ${character.motivation} ${character.arc}`,
    ) * 6;

  if (character.role === "protagonist") score += 1.5;
  if (character.role === "antagonist") score += 1;

  return score;
}

function selectCharacters(
  storyBible: PromptStoryBible,
  _focusText: string,
  _recentText: string,
  outline?: PromptChapterOutline,
  _narrativeState?: PromptNarrativeState,
  _generationMode: "interactive" | "autonomous" = "interactive",
  _localSceneText = "",
): PromptCharacter[] {
  // DETERMINISTIC: Use only the characters specified in the chapter outline
  if (outline?.characters?.length) {
    return outline.characters
      .map((characterName) => {
        const character = storyBible.characters.find((char) =>
          [char.name, ...(char.nicknames || [])].some(
            (name) => name.toLowerCase() === characterName.toLowerCase(),
          ),
        );
        return character;
      })
      .filter((character): character is PromptCharacter => Boolean(character));
  }

  // Fallback: no characters selected if outline doesn't specify
  return [];
}

function _scoreLocation(
  location: PromptLocation,
  focusText: string,
  recentText: string,
  outline?: PromptChapterOutline,
  narrativeState?: PromptNarrativeState,
  generationMode: "interactive" | "autonomous" = "interactive",
  localSceneText = "",
): number {
  let score = 0;
  const aliases = [location.name];
  const localHits = aliasMentions(localSceneText, aliases);
  const stateMatch = narrativeState?.location
    ? aliasMentions(narrativeState.location, aliases) > 0
    : false;

  if (
    generationMode === "interactive" &&
    localSceneText.trim().length > 0 &&
    localHits === 0 &&
    !stateMatch
  ) {
    return 0;
  }

  if (outline?.location && aliasMentions(outline.location, aliases) > 0)
    score += 10;
  if (stateMatch) score += 12;
  score += localHits * 6;
  score += aliasMentions(focusText, aliases) * 4;
  score += aliasMentions(recentText, aliases) * 3;
  score +=
    lexicalOverlap(
      focusText,
      `${location.description} ${location.significance}`,
    ) * 5;

  return score;
}

function selectLocations(
  storyBible: PromptStoryBible,
  _focusText: string,
  _recentText: string,
  outline?: PromptChapterOutline,
  _narrativeState?: PromptNarrativeState,
  _generationMode: "interactive" | "autonomous" = "interactive",
  _localSceneText = "",
): PromptLocation[] {
  const locations = storyBible.world?.locations || [];

  // DETERMINISTIC: Use only the location specified in the chapter outline
  if (outline?.location) {
    const outlineLocation = locations.find(
      (location) =>
        location.name.toLowerCase() === outline.location?.toLowerCase(),
    );
    if (outlineLocation) return [outlineLocation];
  }

  return [];
}

function scorePlotThread(
  thread: PromptPlotThread,
  focusText: string,
  outline?: PromptChapterOutline,
  selectedThreadIds?: string[],
): number {
  let score = 0;

  if ((selectedThreadIds || []).includes(thread.id)) score += 14;
  score += aliasMentions(focusText, [thread.name]) * 5;
  score +=
    lexicalOverlap(focusText, `${thread.name} ${thread.description}`) * 6;

  if (outline) {
    score +=
      lexicalOverlap(
        outline.summary || "",
        `${thread.name} ${thread.description}`,
      ) * 4;
    for (const beat of outline.beats || []) {
      score += lexicalOverlap(beat, `${thread.name} ${thread.description}`) * 3;
    }
  }

  if (thread.status === "active") score += 1;
  return score;
}

function selectPlotThreads(
  storyBible: PromptStoryBible,
  focusText: string,
  outline?: PromptChapterOutline,
  selectedThreadIds?: string[],
  generationMode: "interactive" | "autonomous" = "interactive",
  currentChapterNumber?: number,
): PromptPlotThread[] {
  const threads = (storyBible.plotStructure?.plotThreads || []).filter(
    (thread) => {
      if (!currentChapterNumber) return true;
      if (thread.introducedIn && thread.introducedIn > currentChapterNumber)
        return false;
      if (thread.resolvedIn && thread.resolvedIn < currentChapterNumber)
        return false;
      return true;
    },
  );

  if (generationMode === "interactive") {
    return [];
  }

  const ranked = threads
    .map((thread) => ({
      thread,
      score: scorePlotThread(thread, focusText, outline, selectedThreadIds),
    }))
    .sort((left, right) => right.score - left.score)
    .filter((entry) => entry.score > 0)
    .slice(0, 4)
    .map((entry) => entry.thread);

  if (ranked.length > 0) return ranked;

  const explicitlySelected = threads.filter((thread) =>
    (selectedThreadIds || []).includes(thread.id),
  );
  if (explicitlySelected.length > 0) return explicitlySelected.slice(0, 4);

  return threads.filter((thread) => thread.status === "active").slice(0, 3);
}

function selectWorldRules(
  storyBible: PromptStoryBible,
  focusText: string,
): string[] {
  const rules = storyBible.world?.rules || [];
  return rules
    .map((rule) => ({ rule, score: lexicalOverlap(focusText, rule) }))
    .sort((left, right) => right.score - left.score)
    .slice(0, 4)
    .map((entry) => entry.rule)
    .filter(Boolean)
    .map((rule) => clip(rule, PROMPT_CONTEXT_LIMITS.rule));
}

function selectRelevantBeats(
  outline: PromptChapterOutline | undefined,
  cleanBefore: string,
  cleanAfter: string,
  userPrompt: string,
  generationMode: "interactive" | "autonomous",
  autonomousState?: AutonomousPromptState,
): RelevantBeatSelection {
  const beats = outline?.beats?.filter(Boolean) || [];
  if (beats.length === 0) {
    return {
      beats: [],
      indexes: [],
      bridgeToAfterText: cleanAfter.trim().length > 0,
    };
  }

  if (generationMode === "autonomous") {
    const selected = new Set<number>();
    const queue = [
      autonomousState?.mandatoryBeat || "",
      ...(autonomousState?.remainingPlotPoints || []).slice(0, 3),
    ].filter(Boolean);

    for (const queuedBeat of queue) {
      const directIndex = beats.findIndex((beat) => beat === queuedBeat);
      if (directIndex >= 0) {
        selected.add(directIndex);
        continue;
      }

      const fuzzyIndex = beats
        .map((beat, index) => ({
          index,
          score: lexicalOverlap(beat, queuedBeat),
        }))
        .sort((left, right) => right.score - left.score)[0];

      if (fuzzyIndex && fuzzyIndex.score > 0.18) {
        selected.add(fuzzyIndex.index);
      }
    }

    if (selected.size === 0) {
      selected.add(0);
    }

    const indexes = [...selected]
      .sort((left, right) => left - right)
      .slice(0, 3);
    return {
      beats: indexes.map((index) => beats[index]),
      indexes,
      bridgeToAfterText: false,
    };
  }

  // Beat sequence tracking: determine current beat position (handles case where starting fresh)
  const beforeText = cleanBefore.toLowerCase();
  let currentBeatIndex = 0;

  // Find the most recently completed beat (not perfect, but tracks approximate position)
  for (let i = beats.length - 1; i >= 0; i--) {
    const beatText = beats[i].toLowerCase();
    // Simple keyword check for beat completion
    if (beforeText.includes(beatText.slice(0, 50))) {
      currentBeatIndex = i;
      break;
    }
  }

  // For interactive mode, determine appropriate beat focus based on current position
  if (generationMode === "interactive") {
    // If starting fresh (minimal context), focus on first beat
    if (cleanBefore.trim().length < 100) {
      const indexes = [];
      // Show first 2 beats for context, but write them at proper pace
      const requiredBeatCount = Math.min(2, beats.length);
      for (let i = 0; i < requiredBeatCount; i++) {
        indexes.push(i);
      }
      return {
        beats: indexes.map((index) => beats[index]),
        indexes,
        bridgeToAfterText: cleanAfter.trim().length > 0,
      };
    }

    // For interactive mode with established narrative, show current position
    const startIndex = currentBeatIndex;
    // Show 2 beats for context - current and next
    const endIndex = Math.min(startIndex + 1, beats.length - 1);

    const indexes = [];
    for (let i = startIndex; i <= endIndex; i++) {
      indexes.push(i);
    }
    return {
      beats: indexes.map((index) => beats[index]),
      indexes,
      bridgeToAfterText: cleanAfter.trim().length > 0,
    };
  }

  // For autonomous mode, always show entire outline beats sequentially
  const endIndex = Math.min(currentBeatIndex + 2, beats.length - 1);
  const indexes = [];
  for (let i = currentBeatIndex; i <= endIndex; i++) {
    indexes.push(i);
  }

  return {
    beats: indexes.map((index) => beats[index]),
    indexes,
    bridgeToAfterText: cleanAfter.trim().length > 0,
  };
}

function selectCraftPatterns(
  craftPatterns: PromptCraftPattern[],
  focusText: string,
): PromptCraftPattern[] {
  const filtered = craftPatterns
    .filter((pattern) => pattern.effectiveness > 0.72)
    .map((pattern) => ({
      pattern,
      score:
        pattern.effectiveness * 2 +
        lexicalOverlap(focusText, `${pattern.category} ${pattern.pattern}`) * 6,
    }))
    .sort((left, right) => right.score - left.score);

  const selected: PromptCraftPattern[] = [];
  const seenCategories = new Set<string>();

  for (const entry of filtered) {
    const categoryKey = entry.pattern.category || entry.pattern.id;
    if (seenCategories.has(categoryKey)) continue;
    selected.push(entry.pattern);
    seenCategories.add(categoryKey);
    if (selected.length >= 4) break;
  }

  return selected;
}

function selectLifetimeInsights(
  insights: PromptLifetimeInsight[],
  focusText: string,
): PromptLifetimeInsight[] {
  return insights
    .map((insight) => ({
      insight,
      score:
        insight.strength * 4 + lexicalOverlap(focusText, insight.content) * 6,
    }))
    .sort((left, right) => right.score - left.score)
    .slice(0, 4)
    .map((entry) => entry.insight);
}

function buildPreferenceMemoryLines(
  storyBible: PromptStoryBible | null,
  preferenceMemory: PromptPreferenceMemory | undefined,
): string[] {
  if (!preferenceMemory) {
    return [];
  }

  const lines: string[] = [];
  const storyPov = storyBible?.styleDirectives?.pov?.trim();
  const storyTense = storyBible?.styleDirectives?.tense?.trim();

  if (preferenceMemory.preferredPov) {
    if (!storyPov) {
      lines.push(
        `- POV: ${preferenceMemory.preferredPov} — hold this unless the scene has already established its own.`,
      );
    } else if (
      storyPov.toLowerCase() !== preferenceMemory.preferredPov.toLowerCase()
    ) {
      lines.push(
        `- POV: ${preferenceMemory.preferredPov} — hold this unless the scene has already established its own.`,
      );
    }
  }

  if (preferenceMemory.preferredTense) {
    if (!storyTense) {
      lines.push(
        `- Tense: ${preferenceMemory.preferredTense} — hold this unless the scene has already established its own.`,
      );
    } else if (
      storyTense.toLowerCase() !== preferenceMemory.preferredTense.toLowerCase()
    ) {
      lines.push(
        `- Tense: ${preferenceMemory.preferredTense} — hold this unless the scene has already established its own.`,
      );
    }
  }

  if (preferenceMemory.enableContinuityChecks) {
    lines.push(
      "- Named entities, chronology, and spatial continuity are load-bearing. Keep them exact.",
    );
  }

  return lines;
}

function buildPersistentDirectionLines(
  preferenceMemory: PromptPreferenceMemory | undefined,
  projectMemory: PromptProjectMemory | undefined,
): string[] {
  const lines: string[] = [];
  const globalDirections = (preferenceMemory?.persistentDirections || "")
    .split(/\n+/)
    .map((line) => line.replace(/^[-*]\s*/, "").trim())
    .filter(Boolean);

  for (const line of globalDirections.slice(0, 6)) {
    lines.push(`- ${clip(line, 220)}`);
  }
  for (const line of (projectMemory?.authorDirections || []).slice(0, 6)) {
    if (globalDirections.some((existing) => existing === line)) continue;
    lines.push(`- ${clip(line, 220)}`);
  }

  return lines.slice(0, 6);
}

function buildStyleGuardrails(
  storyBible: PromptStoryBible | null,
  styleFingerprint: PromptStyleFingerprint | null | undefined,
): string[] {
  const lines: string[] = [];

  if (storyBible?.styleDirectives) {
    const directives = storyBible.styleDirectives;
    lines.push(`- POV: ${directives.pov || "preserve the established POV"}`);
    lines.push(
      `- Tense: ${directives.tense || "preserve the established tense"}`,
    );
    if (directives.proseStyle)
      lines.push(`- Prose style: ${clip(directives.proseStyle, 150)}`);
    if (directives.dialogueStyle)
      lines.push(`- Dialogue style: ${clip(directives.dialogueStyle, 150)}`);
  }

  if (!styleFingerprint) {
    return lines;
  }

  if (styleFingerprint.toneDescriptor) {
    lines.push(`- Tone target: ${clip(styleFingerprint.toneDescriptor, 140)}`);
  }

  if (styleFingerprint.avgSentenceLength > 0) {
    const vocabulary =
      styleFingerprint.vocabularyComplexity < 0.4
        ? "accessible"
        : styleFingerprint.vocabularyComplexity > 0.7
          ? "sophisticated"
          : "moderate";

    lines.push(
      `- Sentence rhythm: average ${Math.round(styleFingerprint.avgSentenceLength)} words; ${styleFingerprint.showVsTellRatio > 0.6 ? "leans visual/showing" : "balanced show-vs-tell"}; vocabulary ${vocabulary}`,
    );
  }

  if (styleFingerprint.dialogueTags?.preferred?.length) {
    lines.push(
      `- Dialogue tags to favor: ${styleFingerprint.dialogueTags.preferred.slice(0, 4).join(", ")}`,
    );
  }

  if (styleFingerprint.proseTechniques?.length) {
    lines.push(
      `- Prose techniques to lean on: ${styleFingerprint.proseTechniques.slice(0, 3).join(", ")}`,
    );
  }

  if (styleFingerprint.avoidances?.length) {
    lines.push(
      `- Avoid: ${styleFingerprint.avoidances.slice(0, 4).join(", ")}`,
    );
  }

  if (styleFingerprint.strengthAreas?.length) {
    lines.push(
      `- Preserve strengths: ${styleFingerprint.strengthAreas.slice(0, 3).join(", ")}`,
    );
  }

  return lines;
}

function buildVariationGuardrails(
  styleFingerprint: PromptStyleFingerprint | null | undefined,
): string[] {
  const lines: string[] = [
    "- Move the passage through emotional contrast — let beats shift register rather than sustain one note.",
    "- Vary sentence openings, paragraph lengths, and clause structure so each paragraph has its own shape.",
    "- Rotate image families and sensory textures across paragraphs; let each one arrive fresh.",
    "- Render feeling through action, physical detail, and subtext.",
  ];

  if (styleFingerprint?.emotionalPalette?.length) {
    lines.push(
      `- Emotional colors available in this voice: ${styleFingerprint.emotionalPalette.slice(0, 6).join(", ")}`,
    );
  }

  if (styleFingerprint?.verbChoices?.emotion?.length) {
    lines.push(
      `- Fresh action/physical cues to draw from: ${styleFingerprint.verbChoices.emotion.slice(0, 6).join(", ")}`,
    );
  }

  return lines;
}

function buildNonfictionContext(
  userPrompt: string,
  contextWindow: PromptContextWindow,
): CuratedPromptBuildResult {
  const cleanedPrompt = userPrompt.replace("[NONFICTION]", "").trim();
  const systemPrompt = [
    "You are an expert educational writer creating clear, engaging nonfiction content.",
    'Output ONLY the content - no meta-commentary, no "here\'s the content" preambles.',
    "",
    "## NONFICTION WRITING PRINCIPLES",
    "- Lead with the most important information",
    "- Use clear topic sentences for each paragraph",
    "- Support claims with specific examples or evidence",
    "- Define technical terms when first introduced",
    "- Use transitions to connect ideas logically",
    "- Vary sentence length for readability",
    "- Break complex topics into digestible chunks",
    "",
    "## FORMATTING RULES",
    "- Use blank lines between paragraphs",
    "- Use headers (## or ###) to organize sections",
    "- Use bullet points for lists of 3+ items",
    "- Use numbered lists for sequential steps",
    "- Bold key terms and concepts",
    "",
    "## TONE",
    "- Authoritative but accessible",
    "- Engaging without being casual",
    "- Confident but not condescending",
  ].join("\n");

  const before = clipTail(
    normalizeNarrativeText(contextWindow.before),
    Math.min(30000, TOKEN_LIMITS.MAIN_GENERATION.input),
  );
  const after = clip(
    normalizeNarrativeText(contextWindow.after),
    Math.min(12000, TOKEN_LIMITS.MAIN_GENERATION.input),
  );

  const userParts: string[] = [];

  if (before) {
    userParts.push("=== TEXT BEFORE CURSOR (continue from here) ===");
    userParts.push(before);
    userParts.push("");
  }

  userParts.push("=== CONTINUE WRITING HERE ===");
  userParts.push("");

  if (after) {
    userParts.push("=== TEXT AFTER CURSOR (write toward this) ===");
    userParts.push(after);
    userParts.push("");
  }

  if (cleanedPrompt) {
    userParts.push("=== SPECIFIC INSTRUCTION ===");
    userParts.push(cleanedPrompt);
  }

  return {
    systemPrompt,
    userMessage: userParts.join("\n"),
    selectionSummary: {
      mode: "interactive",
      chapterTitle: null,
      characterNames: [],
      locationNames: [],
      plotThreads: [],
      worldRules: 0,
      craftPatterns: 0,
      lifetimeInsights: 0,
      projectMemoryEntries: 0,
      usedStoryBible: false,
      usedStyleFingerprint: false,
      usedPreferenceMemory: false,
      usedPlannerBrief: false,
    },
  };
}

export function buildCuratedGenerationContext(
  options: CuratedPromptBuildOptions,
): CuratedPromptBuildResult {
  const generationMode = options.generationMode || "interactive";
  if (options.userPrompt.includes("[NONFICTION]")) {
    return buildNonfictionContext(options.userPrompt, options.contextWindow);
  }

  const chapter = findCurrentChapter(options.project, options.chapterId);
  const outline = findCurrentOutline(options.project, options.chapterId);
  const currentChapterNumber = findCurrentChapterNumber(
    options.project,
    options.chapterId,
  );
  const storyBible = options.project.storyBible;
  const styleFingerprint = options.styleFingerprint || null;
  const craftPatterns = options.craftPatterns || [];
  const preferenceMemory = options.preferenceMemory;

  const beforeLimit =
    generationMode === "autonomous"
      ? Math.min(
          PROMPT_CONTEXT_LIMITS.autonomousBefore,
          TOKEN_LIMITS.AUTONOMOUS_ITERATE.input,
        )
      : Math.min(
          PROMPT_CONTEXT_LIMITS.interactiveBefore,
          TOKEN_LIMITS.MAIN_GENERATION.input,
        );
  const afterLimit =
    generationMode === "autonomous"
      ? 0
      : Math.min(
          PROMPT_CONTEXT_LIMITS.interactiveAfter,
          TOKEN_LIMITS.MAIN_GENERATION.input,
        );

  const cleanBefore = clipTail(
    normalizeNarrativeText(options.contextWindow.before),
    beforeLimit,
  );
  const cleanAfter = clip(
    normalizeNarrativeText(options.contextWindow.after),
    afterLimit,
  );
  const hasLocalNarrativeContext =
    cleanBefore.trim().length + cleanAfter.trim().length > 300;
  const localSceneLocked =
    generationMode === "interactive" && hasLocalNarrativeContext;
  const relevantBeatSelection = selectRelevantBeats(
    outline,
    cleanBefore,
    cleanAfter,
    options.userPrompt,
    generationMode,
    options.autonomousState,
  );
  const relevantBeats = relevantBeatSelection.beats;
  const localSceneText = [
    cleanBefore.slice(-6000),
    cleanAfter.slice(0, 3000),
    options.narrativeState?.povCharacter || "",
    options.narrativeState?.location || "",
    ...(outline?.characters || []),
  ]
    .filter(Boolean)
    .join("\n");
  const chapterSummaryForPrompt =
    generationMode === "autonomous" ? outline?.summary || "" : "";

  const focusText = [
    options.userPrompt,
    localSceneLocked ? "" : options.sceneDirective || "",
    cleanBefore.slice(-4000),
    cleanAfter.slice(0, 2000),
    outline?.title || "",
    chapterSummaryForPrompt,
    ...relevantBeats,
    ...(generationMode === "interactive" && hasLocalNarrativeContext
      ? []
      : outline?.characters || []),
    outline?.location || "",
    outline?.timeframe || "",
    options.narrativeState?.time || "",
    options.narrativeState?.location || "",
    options.narrativeState?.povCharacter || "",
    ...(options.autonomousState?.remainingPlotPoints || []).slice(0, 3),
    options.autonomousState?.mandatoryBeat || "",
  ]
    .filter(Boolean)
    .join("\n");

  const selectedCharacters = storyBible
    ? selectCharacters(
        storyBible,
        focusText,
        cleanBefore,
        outline,
        options.narrativeState,
        generationMode,
        localSceneText,
      )
    : [];
  const selectedLocations = storyBible
    ? selectLocations(
        storyBible,
        focusText,
        cleanBefore,
        outline,
        options.narrativeState,
        generationMode,
        localSceneText,
      )
    : [];
  const selectedThreads = storyBible
    ? selectPlotThreads(
        storyBible,
        focusText,
        outline,
        options.autonomousState?.selectedThreadIds,
        generationMode,
        currentChapterNumber,
      )
    : [];
  const worldRules = storyBible ? selectWorldRules(storyBible, focusText) : [];
  const selectedCraftPatterns = selectCraftPatterns(craftPatterns, focusText);
  const selectedLifetimeInsights = selectLifetimeInsights(
    options.lifetimeInsights || [],
    focusText,
  );
  const preferenceMemoryLines = buildPreferenceMemoryLines(
    storyBible,
    preferenceMemory,
  );
  const persistentDirectionLines = buildPersistentDirectionLines(
    preferenceMemory,
    options.projectMemory,
  );
  const styleGuardrails = buildStyleGuardrails(storyBible, styleFingerprint);
  const variationGuardrails = buildVariationGuardrails(styleFingerprint);
  const parts: string[] = [];

  // CRITICAL: If user provided a steering instruction, make it the PRIMARY directive
  const cleanedUserPrompt = options.userPrompt
    .replace("[NONFICTION]", "")
    .trim();
  const hasUserSteering = cleanedUserPrompt.length > 0;

  parts.push(
    "Write the next passage, drawing on the established story world below.",
  );
  parts.push("");

  // PRIME DIRECTIVE - User steering takes priority
  if (hasUserSteering) {
    parts.push("⚠️ CRITICAL PRIORITY - USER STEERING INSTRUCTION:");
    parts.push(
      `The author has provided specific direction for this generation. THIS TAKES PRECEDENCE over story bible beats and outlines.`,
    );
    parts.push(`**Author's instruction: ${cleanedUserPrompt}**`);
    parts.push("");
    parts.push(
      "Execute the author's steering instruction while maintaining consistency with the story bible. If there is any tension between the instruction and the bible, FOLLOW THE AUTHOR'S INSTRUCTION.",
    );
    parts.push("");
  }

  if (persistentDirectionLines.length > 0) {
    parts.push("## PERSISTENT AUTHOR DIRECTIONS");
    parts.push(
      "These are durable author directives. Treat them as standing guidance unless the author gives a more specific instruction for this pass.",
    );
    parts.push(...persistentDirectionLines);
    parts.push("");
  }

  parts.push("CORE WRITING PRINCIPLES:");
  parts.push("- Write vivid, specific prose that brings scenes to life.");
  parts.push("- Use concrete sensory details and precise language.");
  parts.push(
    "- Draw naturally from the Story Bible; weave details organically into the narrative.",
  );
  parts.push(
    "- Honor established character voices, motivations, and relationships from the character dossiers.",
  );
  parts.push(
    "- Integrate the chapter outline beats naturally into compelling scenes, BUT defer to the author's steering instruction if present.",
  );
  parts.push(
    "- Every required beat should enhance the story flow without feeling forced.",
  );
  parts.push("");
  parts.push("STORY BIBLE GUIDANCE:");
  parts.push(
    "- Let characters bring their established backstories and relationships to life in the moment.",
  );
  parts.push(
    "- Use canonical locations and worldbuilding as the rich backdrop for scenes.",
  );
  parts.push(
    "- Plot threads develop naturally as part of character actions and consequences.",
  );
  parts.push(
    "- World rules shape what's possible, but let stories breathe within those bounds.",
  );
  parts.push(
    "- When referencing established elements, trust your Story Bible knowledge to guide descriptions naturally.",
  );
  parts.push("");
  parts.push(
    "Output only the story text, continuing directly from the cursor position.",
  );
  parts.push("");

  if (storyBible) {
    parts.push("## STORY BIBLE CANON (USE AS SOURCE OF TRUTH)");
    if (storyBible.premise?.logline)
      parts.push(`- Logline: ${clip(storyBible.premise.logline, 2000)}`);
    if (storyBible.premise?.tone)
      parts.push(`- Tone: ${clip(storyBible.premise.tone, 400)}`);
    if (storyBible.premise?.themes?.length)
      parts.push(
        `- Themes: ${storyBible.premise.themes.slice(0, 12).join(", ")}`,
      );

    if (storyBible.characters?.length) {
      parts.push("- Characters:");
      for (const character of storyBible.characters) {
        parts.push(
          `  - ${character.name} (${character.role || "unknown"}): ${clip(character.description || "No description recorded.", PROMPT_CONTEXT_LIMITS.description)}`,
        );
        if (character.motivation)
          parts.push(
            `    Motivation: ${clip(character.motivation, PROMPT_CONTEXT_LIMITS.motivation)}`,
          );
        if (character.backstory)
          parts.push(
            `    Backstory: ${clip(character.backstory, PROMPT_CONTEXT_LIMITS.description)}`,
          );
        if (character.arc)
          parts.push(
            `    Arc: ${clip(character.arc, PROMPT_CONTEXT_LIMITS.motivation)}`,
          );
        if (character.fears?.length)
          parts.push(`    Fears: ${character.fears.slice(0, 6).join(", ")}`);
        if (character.flaw)
          parts.push(`    Flaw: ${clip(character.flaw, 300)}`);
        if (character.voice?.speechPatterns?.length)
          parts.push(
            `    Voice: ${character.voice.speechPatterns.slice(0, 6).join(", ")}`,
          );
        if (character.cognitiveFilter) {
          parts.push(
            `    Cognitive filter: ${character.cognitiveFilter.primaryMode}; ${clip(character.cognitiveFilter.internalLanguage, 600)}`,
          );
          if (character.cognitiveFilter.blindSpot)
            parts.push(
              `    Blind spot: ${clip(character.cognitiveFilter.blindSpot, 400)}`,
            );
          if (character.cognitiveFilter.repeatingThoughtLoop)
            parts.push(
              `    Thought loop: ${clip(character.cognitiveFilter.repeatingThoughtLoop, 400)}`,
            );
        }
      }
    }

    if (storyBible.world) {
      if (storyBible.world.setting)
        parts.push(`- World setting: ${clip(storyBible.world.setting, 1500)}`);
      if (storyBible.world.timePeriod)
        parts.push(`- Time period: ${clip(storyBible.world.timePeriod, 800)}`);
      if (storyBible.world.rules?.length)
        parts.push(
          `- World rules: ${storyBible.world.rules.map((rule) => clip(rule, PROMPT_CONTEXT_LIMITS.rule)).join(" | ")}`,
        );
      if (storyBible.world.locations?.length) {
        parts.push("- Locations:");
        for (const location of storyBible.world.locations) {
          parts.push(
            `  - ${location.name}: ${clip(location.description || location.significance || "Established location.", PROMPT_CONTEXT_LIMITS.description)}`,
          );
        }
      }
    }

    if (storyBible.plotStructure?.plotThreads?.length) {
      parts.push("- Plot threads:");
      for (const thread of storyBible.plotStructure.plotThreads) {
        parts.push(
          `  - ${thread.name} (${thread.status || "active"}): ${clip(thread.description || "Established thread.", PROMPT_CONTEXT_LIMITS.plotThread)}`,
        );
        if (thread.currentState)
          parts.push(`    Current: ${clip(thread.currentState, 600)}`);
        if (thread.nextMilestone)
          parts.push(`    Next: ${clip(thread.nextMilestone, 600)}`);
        if (thread.introducedIn)
          parts.push(`    Introduced in chapter: ${thread.introducedIn}`);
        if (thread.resolvedIn)
          parts.push(`    Resolved in chapter: ${thread.resolvedIn}`);
      }
    }

    if (storyBible.chapterOutlines?.length) {
      // Only show chapter outlines for the CURRENT chapter being written
      // Hide future chapters to prevent AI from pulling ahead/spoiling
      const currentOutline = outline; // This is already filtered to current chapter

      if (currentOutline) {
        parts.push("- Chapter outlines:");
        parts.push(
          `  - Chapter ${currentOutline.chapterNumber}: ${clip(currentOutline.title || "Untitled", 400)} — ${clip(currentOutline.summary || "", 1200)}`,
        );
        if (currentOutline.beats?.length) {
          parts.push(
            `    Required beats: ${currentOutline.beats.map((beat) => clip(beat, 400)).join(" | ")}`,
          );
        }
        if (currentOutline.location)
          parts.push(`    Location: ${clip(currentOutline.location, 400)}`);
        if (currentOutline.timeframe)
          parts.push(`    Timeframe: ${clip(currentOutline.timeframe, 400)}`);
      }
      // Don't show future chapter outlines - they contain spoilers that make the AI rush ahead
    }

    if (storyBible.styleDirectives) {
      parts.push(
        `- Style: POV ${storyBible.styleDirectives.pov || "match the established POV"}, tense ${storyBible.styleDirectives.tense || "match the established tense"}, prose ${clip(storyBible.styleDirectives.proseStyle || "", 600)}, dialogue ${clip(storyBible.styleDirectives.dialogueStyle || "", 600)}`,
      );
    }
    parts.push("");
  }

  if (storyBible?.premise) {
    parts.push("## STORY NORTH STAR");
    if (storyBible.premise.logline)
      parts.push(`- Logline: ${clip(storyBible.premise.logline, 220)}`);
    if (storyBible.premise.tone)
      parts.push(`- Tone: ${storyBible.premise.tone}`);
    if (storyBible.premise.themes?.length)
      parts.push(
        `- Themes in play: ${storyBible.premise.themes.slice(0, 4).join(", ")}`,
      );
    parts.push("");
  }

  if (outline) {
    parts.push("## CURRENT CHAPTER");
    parts.push(
      `- Chapter: ${outline.title || chapter?.title || `Chapter ${outline.chapterNumber}`}`,
    );
    if (chapterSummaryForPrompt)
      parts.push(`- Chapter intent: ${clip(chapterSummaryForPrompt, 260)}`);
    if (outline.location) parts.push(`- Primary location: ${outline.location}`);
    if (outline.timeframe) parts.push(`- Timeframe: ${outline.timeframe}`);
    if (outline.beats?.length) {
      parts.push("## CHAPTER BEATS");
      for (const beat of outline.beats) {
        parts.push(`- ${clip(beat, 220)}`);
      }
      const beatCount = outline.beats.length;
      parts.push(
        `- This chapter has ${beatCount} beat${beatCount > 1 ? "s" : ""}. Let them breathe across the full chapter length.`,
      );
      parts.push(
        `- Give each beat full scene development — action, dialogue, sensory detail.`,
      );
      if (beatCount > 1) {
        parts.push(
          `- Stay with the current beat. Let the next one arrive when this one is earned.`,
        );
      }
    }
    if (relevantBeats.length > 0) {
      parts.push(
        generationMode === "autonomous"
          ? "- Beat queue in scope:"
          : relevantBeatSelection.bridgeToAfterText
            ? "- Cursor-local beat anchors:"
            : "- Local chapter beats in scope:",
      );
      for (const beat of relevantBeats) {
        parts.push(`  - ${clip(beat, 180)}`);
      }
    }
    if (
      generationMode === "interactive" &&
      relevantBeatSelection.bridgeToAfterText
    ) {
      parts.push(
        "- Treat text-after-cursor as already written. Bridge into it cleanly and carry it forward.",
      );
      parts.push(
        "- Stay in the current scene until a real transition is earned.",
      );
    } else if (generationMode === "interactive") {
      parts.push(
        "- Advance from the current local beat. Let the chapter build forward from here.",
      );
    }
    if (generationMode === "interactive" && hasLocalNarrativeContext) {
      parts.push(
        "- The visible scene is the source of truth. Follow what's on the page.",
      );
    }
    parts.push("");
  }

  if (selectedCharacters.length > 0) {
    parts.push("## ACTIVE CAST");
    for (const character of selectedCharacters) {
      parts.push(
        ...summarizeCharacter(
          character,
          storyBible?.characters || [],
          options.narrativeState,
          generationMode,
          localSceneText,
        ),
      );
    }
    parts.push("");
  }

  if (
    selectedLocations.length > 0 ||
    worldRules.length > 0 ||
    storyBible?.world?.setting ||
    storyBible?.world?.timePeriod
  ) {
    parts.push("## WORLD AND SCENE RAILS");
    if (storyBible?.world?.setting)
      parts.push(`- Setting anchor: ${clip(storyBible.world.setting, 180)}`);
    if (storyBible?.world?.timePeriod)
      parts.push(`- Time period: ${clip(storyBible.world.timePeriod, 120)}`);
    for (const location of selectedLocations) {
      parts.push(
        `- Location in play: ${location.name} - ${clip(location.description || location.significance || "Established location.", PROMPT_CONTEXT_LIMITS.description)}`,
      );
    }
    for (const rule of worldRules) {
      parts.push(`- World rule: ${rule}`);
    }
    parts.push("");
  }

  if (selectedThreads.length > 0) {
    parts.push("## PLOT THREADS IN PLAY");
    for (const thread of selectedThreads) {
      parts.push(
        `- ${thread.name} (${thread.status || "active"}): ${clip(thread.description || "Established thread.", PROMPT_CONTEXT_LIMITS.plotThread)}`,
      );
    }
    parts.push("");
  }

  if (styleGuardrails.length > 0) {
    parts.push("## STYLE");
    parts.push(...styleGuardrails);
    parts.push("");
  }

  if (variationGuardrails.length > 0) {
    parts.push("## RANGE AND VARIATION");
    parts.push(...variationGuardrails);
    parts.push("");
  }

  if (selectedLifetimeInsights.length > 0) {
    parts.push("## LIFETIME MEMORY");
    for (const insight of selectedLifetimeInsights) {
      parts.push(`- ${clip(insight.content, 180)}`);
    }
    parts.push("");
  }

  if (
    (options.projectMemory?.projectPreferences.length || 0) > 0 ||
    (options.projectMemory?.projectEvents.length || 0) > 0
  ) {
    parts.push("## PROJECT MEMORY");
    if ((options.projectMemory?.projectPreferences.length || 0) > 0) {
      parts.push("Project-specific preferences learned from prior passes:");
      for (const preference of options.projectMemory?.projectPreferences ||
        []) {
        parts.push(`- ${clip(preference, 220)}`);
      }
    }
    if ((options.projectMemory?.projectEvents.length || 0) > 0) {
      parts.push("Important accepted story movement from this project:");
      for (const event of options.projectMemory?.projectEvents || []) {
        parts.push(`- ${clip(event, 240)}`);
      }
    }
    parts.push("");
  }

  if (options.sceneDirective) {
    parts.push("## SCENE BRIEF");
    parts.push(clip(options.sceneDirective, 1400));
    parts.push("");
  }

  const userParts: string[] = [];
  if (cleanBefore.trim().length < 100 && generationMode === "interactive") {
    // FRESH START MODE: Opening the first scene
    userParts.push("=== FIRST SCENE SETUP ===");
    userParts.push("You are starting this scene from the very beginning.");
    userParts.push(
      `Begin this scene exactly according to the first beat in the outline above: "${outline?.beats?.[0] || "Establish the opening moment."}"`,
    );
    userParts.push(
      "Do NOT start with generic thriller or action tropes. Begin with the specific moment/character/setting your first beat calls for.",
    );
    userParts.push("");
  } else if (cleanBefore) {
    userParts.push("=== TEXT BEFORE CURSOR (continue directly from here) ===");
    userParts.push(cleanBefore);
    userParts.push("");
  }

  userParts.push("=== WRITE THE NEXT PASSAGE ===");
  userParts.push("");

  if (cleanAfter) {
    userParts.push("=== TEXT AFTER CURSOR (write toward this) ===");
    userParts.push(cleanAfter);
    userParts.push("");
  }

  // Note: User steering instruction is now prominently displayed in system prompt above
  // We don't repeat it here to avoid dilution and to keep the user message focused on context

  return {
    systemPrompt: parts.join("\n"),
    userMessage: userParts.join("\n"),
    selectionSummary: {
      mode: generationMode,
      chapterTitle: outline?.title || chapter?.title || null,
      characterNames: selectedCharacters.map((character) => character.name),
      locationNames: selectedLocations.map((location) => location.name),
      plotThreads: selectedThreads.map((thread) => thread.name),
      worldRules: worldRules.length,
      craftPatterns: selectedCraftPatterns.length,
      lifetimeInsights: selectedLifetimeInsights.length,
      projectMemoryEntries:
        (options.projectMemory?.projectPreferences.length || 0) +
        (options.projectMemory?.projectEvents.length || 0) +
        persistentDirectionLines.length,
      usedStoryBible: !!storyBible,
      usedStyleFingerprint: !!styleFingerprint,
      usedPreferenceMemory:
        preferenceMemoryLines.length > 0 || persistentDirectionLines.length > 0,
      usedPlannerBrief: !!options.sceneDirective,
    },
  };
}

export function buildCuratedPrompt(options: BuildCuratedPromptOptions): {
  systemPrompt: string;
  userMessage: string;
  debug: Record<string, unknown>;
} {
  const result = buildCuratedGenerationContext({
    project: options.project,
    contextWindow: options.contextWindow,
    userPrompt: options.userPrompt,
    chapterId: options.chapterId,
    sceneDirective: options.scenePlan?.directive,
    styleFingerprint: options.styleFingerprint,
    craftPatterns: options.craftPatterns,
    lifetimeInsights: options.lifetimeInsights,
    preferenceMemory: options.preferenceMemory,
    projectMemory: options.projectMemory,
    narrativeState: options.narrativeState,
    continuityIndex: options.continuityIndex,
    generationMode:
      options.mode === "autonomous" ? "autonomous" : "interactive",
    autonomousState:
      options.mode === "autonomous"
        ? {
            mandatoryBeat: options.mandatoryBeat,
            completedBeats: options.completedBeats,
            remainingPlotPoints: options.remainingPlotPoints,
            selectedThreadIds: options.selectedThreadIds,
          }
        : undefined,
  });

  return {
    systemPrompt: result.systemPrompt,
    userMessage: result.userMessage,
    debug: result.selectionSummary,
  };
}
