export type View =
  | "projects"
  | "editor"
  | "autonomous"
  | "story-bible"
  | "style"
  | "metrics"
  | "settings";

export interface Chapter {
  id: string;
  title: string;
  content: string;
  wordCount: number;
  order: number;
}

export interface ChapterOutline {
  chapterNumber: number;
  title: string;
  summary: string;
  beats: string[];
  characters: string[];
  location: string;
  timeframe: string;
}

export interface Location {
  name: string;
  description: string;
  significance: string;
}

export interface Act {
  number: number;
  name: string;
  description: string;
  keyEvents: string[];
  chapterRange?: {
    start: number;
    end: number;
  };
}

export interface PlotThread {
  id: string;
  name: string;
  type: string;
  description: string;
  status: string;
  introducedIn?: number;
  currentState?: string;
  keyCharacters?: string[];
  tension?: "low" | "medium" | "high" | "critical";
  resolvedIn?: number | null;
  relatedThreads?: string[];
  nextMilestone?: string;
  beats?: string[];
}

export interface CharacterVoice {
  vocabulary: string;
  speechPatterns: string[];
  catchphrases: string[];
}

export interface CognitiveFilter {
  primaryMode:
    | "analytical"
    | "emotional"
    | "instinctive"
    | "ritualistic"
    | "detached"
    | "sensory";
  internalLanguage: string;
  blindSpot: string;
  repeatingThoughtLoop: string;
  forbiddenWords?: string[];
  signatureThoughts?: string[];
}

export interface CharacterRelationship {
  characterId?: string;
  characterName?: string;
  type: string;
  description: string;
}

export interface Character {
  id: string;
  name: string;
  nicknames?: string[];
  role: string;
  description: string;
  backstory: string;
  motivation: string;
  fears: string[];
  flaw: string;
  arc: string;
  voice: CharacterVoice;
  cognitiveFilter?: CognitiveFilter;
  relationships: CharacterRelationship[];
  unrevealed?: boolean;
  spoilers?: string[];
  autoGenerated?: boolean;
}

export interface StoryBible {
  premise: {
    logline: string;
    synopsis: string;
    themes: string[];
    tone: string;
    genre: string;
  };
  characters: Character[];
  world: {
    setting: string;
    timePeriod: string;
    locations: Location[];
    rules: string[];
  };
  plotStructure: {
    acts: Act[];
    plotThreads: PlotThread[];
  };
  chapterOutlines?: ChapterOutline[];
  styleDirectives: {
    pov: string;
    tense: string;
    proseStyle: string;
    dialogueStyle: string;
  };
}

export interface ProjectSummary {
  id: string;
  title: string;
  description: string;
  genre: string;
  wordCount: number;
  chapterCount?: number;
  hasStoryBible?: boolean;
  createdAt: string;
  updatedAt: string;
}

export interface Project extends ProjectSummary {
  content: string;
  chapters: Chapter[];
  storyBible: StoryBible | null;
}

export interface GenerationMetadata {
  tokens: number;
  latencyMs: number;
  attempts: number;
  accepted?: boolean;
  qualityFallback?: boolean;
  provider?: string;
  model?: string;
  scenePromptPlanId?: string;
  plannerModelUsed?: string;
  embeddingModelUsed?: string;
}

export interface GenerationResult {
  text: string;
  wordCount: number;
  qualityScore: number;
  qualityIssues?: string[];
  accepted?: boolean;
  recoveryDraftId?: string;
  endOfChapter?: boolean;
  endOfChapterReason?: string;
  qualityFallback?: boolean;
  qualityFallbackReason?: string;
  continuityScore?: number;
  continuityIssues?: Array<{
    type: string;
    description: string;
    severity: string;
  }>;
  creativeDecisions?: Array<{
    type: string;
    description: string;
    severity: string;
  }>;
  metadata: GenerationMetadata;
}

export interface GenerationRecoveryDraft {
  id: string;
  projectId: string;
  chapterId: string;
  source: string;
  text: string;
  wordCount: number;
  status: "pending" | "persisted" | "dismissed";
  createdAt: string;
  updatedAt: string;
}

export interface AutonomousSession {
  id: string;
  projectId: string;
  chapterId: string;
  actNumber: number;
  status: "running" | "paused" | "completed" | "stopped";
  autoIterate: boolean;
  autoAccept: boolean;
  goal: string;
  targetWords: number;
  generatedWords: number;
  iterations: number;
  plotPointsToHit: string[];
  plotPointsHit: string[];
  selectedThreads: string[];
  startedAt: string;
  pausedAt?: string;
  completedAt?: string;
  mode: "chapter" | "book";
  chaptersToWrite: string[];
  currentChapterIndex: number;
  chaptersCompleted: string[];
  totalBookWords: number;
  wordsPerChapter: number;
  pendingDraft?: string;
  pendingDraftWords?: number;
  pendingDraftEndOfChapter?: boolean;
  pendingDraftEndOfChapterReason?: string;
  lastCommittedContent?: string;
  lastCommittedWords?: number;
  lastCommittedAt?: string;
  lastCommittedChapterId?: string;
  pauseReason?: string;
}

export interface NarrativeState {
  time: string;
  location: string;
  povCharacter: string;
  mood: string;
}

export interface BookProgress {
  currentChapter: number;
  totalChapters: number;
  chaptersCompleted: number;
  totalBookWords: number;
}

export interface ExtractionMetrics {
  passBreakdown: {
    pass: number;
    name: string;
    found: number;
    newAdded: number;
    duplicatesSkipped: number;
    enriched: number;
  }[];
  totalCharactersFound: number;
  totalNewAdded: number;
  totalDuplicatesSkipped: number;
  totalEnriched: number;
}
