export interface Project {
  id: string;
  title: string;
  description: string;
  genre: string;
  content: string;
  wordCount: number;
  chapters: Chapter[];
  storyBible: StoryBible | null;
  createdAt: string;
  updatedAt: string;
}

export interface Chapter {
  id: string;
  title: string;
  content: string;
  wordCount: number;
  order: number;
}

export interface ChapterOutline {
  chapterNumber: number;
  title: string;
  summary: string;
  beats: string[];
  characters: string[];
  location: string;
  timeframe: string;
}

export interface StoryBible {
  premise: {
    logline: string;
    synopsis: string;
    themes: string[];
    tone: string;
    genre: string;
  };
  characters: Character[];
  world: {
    setting: string;
    timePeriod: string;
    locations: Location[];
    rules: string[];
  };
  plotStructure: {
    acts: Act[];
    plotThreads: PlotThread[];
  };
  chapterOutlines: ChapterOutline[];
  styleDirectives: {
    pov: string;
    tense: string;
    proseStyle: string;
    dialogueStyle: string;
  };
}

export interface Character {
  id: string;
  name: string;
  nicknames?: string[];
  role: string;
  description: string;
  backstory: string;
  motivation: string;
  fears: string[];
  flaw: string;
  arc: string;
  unrevealed?: boolean;
  spoilers?: string[];
  voice: {
    vocabulary: string;
    speechPatterns: string[];
    catchphrases: string[];
  };
  relationships: { characterId: string; type: string; description: string }[];
  autoGenerated?: boolean;
  cognitiveFilter?: {
    primaryMode:
      | "analytical"
      | "emotional"
      | "instinctive"
      | "ritualistic"
      | "detached"
      | "sensory";
    internalLanguage: string;
    blindSpot: string;
    repeatingThoughtLoop: string;
    forbiddenWords?: string[];
    signatureThoughts?: string[];
  };
}

export interface Location {
  name: string;
  description: string;
  significance: string;
  autoGenerated?: boolean;
}

export interface Act {
  number: number;
  name: string;
  description: string;
  keyEvents: string[];
  chapterRange?: {
    start: number;
    end: number;
  };
}

export interface PlotThread {
  id: string;
  name: string;
  type: string;
  description: string;
  status: string;
}

export interface StyleFingerprint {
  vocabularyComplexity: number;
  avgSentenceLength: number;
  dialogueRatio: number;
  showVsTellRatio: number;
  passiveVoiceRatio: number;
  adverbDensity: number;
  metaphorFrequency: number;
  pacingScore: number;
  toneDescriptor: string;
  strengthAreas: string[];
  improvementAreas: string[];
  sampleCount: number;
  rawSamples: string[];
  signaturePhrases: string[];
  dialogueTags: { preferred: string[]; avoided: string[] };
  verbChoices: { movement: string[]; speech: string[]; emotion: string[] };
  sentencePatterns: string[];
  paragraphOpeners: string[];
  sceneOpenings: string[];
  tensionTechniques: string[];
  exemplars: string[];
  humorStyle: string;
  emotionalPalette: string[];
  avoidances: string[];
  proseTechniques: string[];
  pacing: string;
}

export interface SceneEvidence {
  id: string;
  source: string;
  text: string;
  score: number;
}

export interface SceneObjective {
  id: string;
  text: string;
  status: "pending" | "covered";
  evidenceIds: string[];
}

export interface ScenePromptPlanRecord {
  id: string;
  projectId: string;
  chapterId?: string;
  createdAt: string;
  sceneGoal: string;
  objectives: SceneObjective[];
  selectedEvidence: SceneEvidence[];
  directive: string;
  plannerModelUsed: string | null;
  embeddingModelUsed: string | null;
}

export interface UserPreferences {
  styleFingerprint: StyleFingerprint | null;
  generationSettings: {
    defaultTemperature: number;
    defaultTopP: number;
    defaultFrequencyPenalty: number;
    defaultPresencePenalty: number;
    defaultTargetWords: number;
    enablePromptPlanner: boolean;
    promptPlannerEmbeddingProvider:
      | "main"
      | "codex"
      | "groq"
      | "openai"
      | "openai-compatible"
      | "anthropic"
      | "google"
      | "ollama";
    promptPlannerEmbeddingModel: string;
    promptPlannerProvider:
      | "main"
      | "codex"
      | "groq"
      | "openai"
      | "openai-compatible"
      | "anthropic"
      | "google"
      | "ollama";
    promptPlannerModel: string;
    storyBibleProvider:
      | "main"
      | "codex"
      | "groq"
      | "openai"
      | "openai-compatible"
      | "anthropic"
      | "google"
      | "ollama";
    storyBibleModel: string;
    promptPlannerTopK: number;
    promptPlannerFallbackMode: "lexical" | "error";
  };
  memorySettings: {
    preferredPov: string;
    preferredTense: string;
    contextWindowSize: number;
    enableContinuityChecks: boolean;
    persistentDirections: string;
  };
  qualitySettings: {
    showScores: boolean;
    minThreshold: number;
  };
  uiPreferences: {
    theme: string;
    fontSize: number;
    showWordCount: boolean;
  };
}

export interface LifetimeInsight {
  id: string;
  type: string;
  content: string;
  strength: number;
  createdAt: string;
}

export interface ProjectMemoryEvent {
  id: string;
  chapterId?: string;
  chapterTitle?: string;
  summary: string;
  characters: string[];
  location: string;
  source: string;
  timestamp: string;
  weight: number;
}

export interface ProjectMemoryPreference {
  id: string;
  content: string;
  strength: number;
  source: string;
  updatedAt: string;
}

export interface ProjectMemory {
  projectId: string;
  updatedAt: string;
  events: ProjectMemoryEvent[];
  preferences: ProjectMemoryPreference[];
}

export interface CraftPattern {
  id: string;
  category: string;
  pattern: string;
  example: string;
  effectiveness: number;
}

export interface LifetimeMemory {
  insights: LifetimeInsight[];
  writingHistory: { date: string; wordsWritten: number; projectId: string }[];
  feedbackHistory: {
    generatedText: string;
    feedback: string;
    reason: string;
    timestamp: string;
  }[];
  projectMemories: ProjectMemory[];
}

export interface ContinuityViolation {
  check: string;
  type: string;
  description: string;
  severity: "error" | "warning";
  fixable: "text" | "bible" | "author";
  fix?: string;
  line?: string;
  character?: string;
}

export interface PassResult {
  check: string;
  pass: boolean;
  violations: ContinuityViolation[];
  weight: number;
  errored?: boolean;
}

export interface ContextWindow {
  before: string;
  after: string;
  cursorPosition: number;
}

export interface ContinuityCheckContext {
  chapterId?: string;
  povCharacterName?: string;
  recentContent?: string;
}

export interface AutonomousSession {
  id: string;
  projectId: string;
  chapterId: string;
  actNumber: number;
  status: "running" | "paused" | "completed" | "stopped";
  autoIterate: boolean;
  autoAccept: boolean;
  goal: string;
  targetWords: number;
  generatedWords: number;
  iterations: number;
  plotPointsToHit: string[];
  plotPointsHit: string[];
  selectedThreads: string[];
  startedAt: string;
  pausedAt?: string;
  completedAt?: string;
  mode: "chapter" | "book";
  chaptersToWrite: string[];
  currentChapterIndex: number;
  chaptersCompleted: string[];
  totalBookWords: number;
  wordsPerChapter: number;
  pendingDraft?: string;
  pendingDraftWords?: number;
  pendingDraftEndOfChapter?: boolean;
  pendingDraftEndOfChapterReason?: string;
  lastCommittedContent?: string;
  lastCommittedWords?: number;
  lastCommittedAt?: string;
  lastCommittedChapterId?: string;
  pauseReason?: string;
}

export interface ContinuityIndex {
  characters: Map<
    string,
    {
      lastLocation: string;
      lastEmotion: string;
      lastAction: string;
      relationships: Record<string, string>;
      updatedAt: number;
    }
  >;
  plotThreads: Map<
    string,
    {
      status: "active" | "resolved" | "paused";
      lastMention: string;
      triggers: string[];
    }
  >;
  worldState: {
    currentTime: string;
    currentLocation: string;
    recentEvents: string[];
  };
  projectHash: string;
}
